# Generated by Django 3.2.6 on 2021-08-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('author', models.CharField(max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.CharField(max_length=10)),
                ('image', models.ImageField(default='images/abc.jpg', null=True, upload_to='images/')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('label', models.CharField(choices=[('new', 'جدید'), ('sale', 'حراج')], max_length=6, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.ManyToManyField(related_name='books', to='books.Category')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['-created'],
            },
        ),
    ]
