# Generated by Django 3.2.6 on 2021-08-29 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcash',
            options={'ordering': ['-valid_to'], 'verbose_name': 'تخفیف - نقدی', 'verbose_name_plural': 'تخفیفات - نقدی'},
        ),
        migrations.AlterModelOptions(
            name='discountpercent',
            options={'ordering': ['-valid_to'], 'verbose_name': 'تخفیف - درصدی', 'verbose_name_plural': 'تخفیفات - درصدی'},
        ),
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.PositiveIntegerField(default=0, verbose_name='فروخته شده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='label',
            field=models.CharField(choices=[('new', 'جدید'), ('sale', 'حراج')], default='None', max_length=6, null=True, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='discountcash',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discountcash',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(800)], verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='discountcash',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='discountcash',
            name='valid_from',
            field=models.DateTimeField(verbose_name='شروع'),
        ),
        migrations.AlterField(
            model_name='discountcash',
            name='valid_to',
            field=models.DateTimeField(verbose_name='انقضا'),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='valid_from',
            field=models.DateTimeField(verbose_name='شزوع'),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='valid_to',
            field=models.DateTimeField(verbose_name='انقضا'),
        ),
    ]
