# Generated by Django 3.2.6 on 2021-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210811_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
