# Generated by Django 3.2.6 on 2021-08-31 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdefaultaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['-city']},
        ),
    ]
