# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_userdefaultaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comment',
        ),
    ]
