# Generated by Django 3.2.6 on 2021-09-02 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='نام کد')),
                ('valid_from', models.DateTimeField(verbose_name='شروع')),
                ('valid_to', models.DateTimeField(verbose_name='انقضا')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف ویژه',
                'verbose_name_plural': 'کد تخفیف ویژه',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('payment', models.BooleanField(default=False, verbose_name='پرداخت')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف ویژه')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='accounts.addresses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاریر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف موردی')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='books.book', verbose_name='کتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سغارش')),
            ],
            options={
                'verbose_name': 'جزییات سغارش ',
                'verbose_name_plural': 'جزییات سغارش',
            },
        ),
    ]
