# Generated by Django 3.2.6 on 2021-08-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210830_0113'),
        ('orders', '0002_auto_20210830_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='accounts.addresses'),
        ),
    ]
