# Generated by Django 3.2.6 on 2021-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
